title: Sarah Lean
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: light # Or use dark

# Profile information
name: Sarah Lean
tagline: Cloud Solution Architect
about-description:I am a highly motivated, thorough and results driven Infrastructure Engineer who, at a young age, fell in love with technology and in my 11+ years in the IT industry, has a deep and wide ranging knowledge of a variety of best-in-breed technologies specializing in Microsoft, VMware and Veeam. Through my work in the IT Managed Services sector I have many years’ experience dealing with IT systems, requirements gathering and stakeholder management from varying industries including the Scottish drinks industry, commercial call centres, manufacturing, and the arts. # Add Discription
pic: sarah3_four.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
website: www.sarahlean.com # Add your website, do not add http://
linkedin: sazlean # Add your Linkedin handle
github: weeyin83 # Add your Github handle
twitter: '@techielass' # Add your Twitter handle

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
