title: Sarah Lean
description: Personal website of Sarah Lean.  Sarah is a technical professional, blogger and user group founder. 
baseurl: # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: light # Or use dark

# Profile information
name: Sarah Lean
tagline: Technologist
about-description: I am a highly motivated, thorough and results driven IT professional.  I fell in love with technology at an early age and have made it my career.  I have a deep and wide ranging knowledge of a variety of best-in-breed technologies. My focus is on Cloud and Hybrid implementations.  I am a professional content creator and am open to opportunities.
 # Add Discription
pic: sarah3_four.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
website: www.gaug.co.uk # Add your website, do not add http://
linkedin: sazlean # Add your Linkedin handle
github: weeyin83 # Add your Github handle
twitter: '@techielass' # Add your Twitter handle

# Tracker
analytics: UA-18889564-1

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
